application:  
version: alpha4
runtime: python
api_version: 1



builtins:
- datastore_admin: on
- remote_api: on


handlers:
- url: /mapreduce(/.*)?
  script: mapreduce/main.py

- url: .*
  script: main.py
